### ISSUE TITLE
Conflict with airbrake with version 4.x of elastic-apm

### ISSUE THREAD

**Issue by mrudult** [elastic/apm-agent-ruby#1023]
## Describe the bug

[ElasticAPM] Couldn't establish connection to APM Server:
"#<SystemStackError: stack level too deep>"

```
#<Thread:0x000056063e834380@/applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:140 run> terminated with exception (report_on_exception is true):
      01 /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm.rb:84:in `agent': stack level too deep (SystemStackError)
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm.rb:93:in `current_transaction'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/spies/http.rb:31:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:10:in `block in perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:9:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/spies/http.rb:32:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:10:in `block in perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
      01   ... 9349 levels...
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/worker.rb:52:in `new'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/worker.rb:52:in `initialize'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:141:in `new'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:141:in `block in boot_worker'
```

## Steps to reproduce

Setup ELK

1. git clone https://github.com/deviantony/docker-elk.git
2. cd docker-elk
3. docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up

Add gems

1. add gem 'elastic-apm' in Gemfile
2. add gem 'airbrake' in Gemfile
3. bundle install
4. rails s

## Expected behavior

Metrics should be sent

## Environment

- **OS**: Ubuntu
- **Ruby version**: 2.6.5
- **Framework and version**: Rails 5.2.5
- **APM Server version**: 7.10.0
- **Agent version**: 4.1.0

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
  service_name: 'Rails app'
  server_url: http://localhost:8200
  secret_token: ''
  central_config: false
  pool_size: 10
  api_buffer_size: 1024
  transaction_sample_rate: 0.2
  capture_headers: false
    ```
  </details>

**Comment by mikker** [comment]
Did you figure out a solution since you closed the issue again?

**Comment by mrudult** [comment]
@mikker I tried it again while reproducing #1024 and it worked fine. Strange!

**Comment by mikker** [comment]
The bug usually appears when, after an Exception, the Agent tries to get a `backtrace`. Happy to hear it went away. Let us know if it comes up again!
