### ISSUE TITLE
APM agent fails to start, "`current_spans': stack level too deep (SystemStackError)"

### ISSUE THREAD

**Issue by slhck** [elastic/apm-agent-ruby#1147]
## Describe the bug

I updated the APM library from 3.x to 4.3.0 recently, within a Rails application's Sidekiq worker. The Sidekiq worker now cannot boot anymore. Downgrading back to APM 3.x made the application work again.

This error appears when starting Sidekiq:

```
worker_1  | 2021-08-20T07:03:01.682Z pid=1 tid=3w1 INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://redis:6379/0"}
worker_1  | {"ts":"2021-08-20T07:03:01.956Z","pid":1,"tid":"3w1","lvl":"INFO","msg":"Booted Rails 6.1.4.1 application in development environment"}
worker_1  | {"ts":"2021-08-20T07:03:01.956Z","pid":1,"tid":"3w1","lvl":"INFO","msg":"Running in ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux-musl]"}
worker_1  | {"ts":"2021-08-20T07:03:01.956Z","pid":1,"tid":"3w1","lvl":"INFO","msg":"See LICENSE and the LGPL-3.0 for licensing details."}
worker_1  | {"ts":"2021-08-20T07:03:01.956Z","pid":1,"tid":"3w1","lvl":"INFO","msg":"Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org"}
worker_1  | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
worker_1  | /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm/instrumenter.rb:163:in `current_spans': stack level too deep (SystemStackError)
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm/instrumenter.rb:226:in `end_span'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm/agent.rb:215:in `end_span'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm.rb:248:in `end_span'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm.rb:305:in `ensure in with_span'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm.rb:305:in `with_span'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm/spies/redis.rb:32:in `call'
worker_1  |     from /usr/local/bundle/gems/prometheus_exporter-0.8.1/lib/prometheus_exporter/instrumentation/method_profiler.rb:15:in `call'
worker_1  |     from /usr/local/bundle/gems/elastic-apm-4.3.0/lib/elastic_apm/spies/redis.rb:33:in `block in call'
worker_1  |      ... 8316 levels...
worker_1  |     from /usr/local/bundle/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
worker_1  |     from /usr/local/bundle/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
worker_1  |     from /usr/local/bundle/bin/bundle:23:in `load'
worker_1  |     from /usr/local/bundle/bin/bundle:23:in `<main>'
```

It seems to be related to [Prometheus Exporter](https://github.com/discourse/prometheus_exporter). The particular error happens only happens with the following Sidekiq config, which loads Prometheus Exporter:

```rb
require 'sidekiq/api'
require 'prometheus_exporter/instrumentation'

SidekiqUniqueJobs.configure do |config|
  config.lock_info = false # true for debugging
  config.logger = Logger.new("/dev/null") if Rails.env.test?
end

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }
  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new
  config.on :startup do
    PrometheusExporter::Instrumentation::ActiveRecord.start(
      custom_labels: { type: "sidekiq" }, #optional params
      config_labels: [:database, :host] #optional params
    )
    PrometheusExporter::Instrumentation::SidekiqQueue.start
    PrometheusExporter::Instrumentation::Process.start type: 'sidekiq'
  end
  at_exit do
    PrometheusExporter::Client.default.stop(wait_timeout_seconds: 10)
  end
  config.server_middleware do |chain|
    chain.add PrometheusExporter::Instrumentation::Sidekiq
  end
  config.death_handlers << PrometheusExporter::Instrumentation::Sidekiq.death_handler

  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end

  config.server_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Server
  end
  SidekiqUniqueJobs::Server.configure(config)
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['REDIS_URL'] }

  config.client_middleware do |chain|
    chain.add SidekiqUniqueJobs::Middleware::Client
  end
end
```

When I uncomment those lines related to Prometheus Exporter, APM boots up.

## Environment

- **OS**: Alpine Linux 3.13
- **Ruby version**: 3.0.1
- **Framework and version**: Rails 6.1.4.1 with Sidekiq 6.2.1
- **APM Server version**: 7.14
- **Agent version**: 4.3.0

## Additional context

I have no other options set for the APM agent. It just receives the URL via environment variable.

**Comment by slhck** [comment]
I see this has been mentioned here: https://github.com/discourse/prometheus_exporter/issues/159#issuecomment-878326213

Feel free to close in case there is nothing that can be done from this Gem's side.

**Comment by mikker** [comment]
The issue you've linked describes both the issue and possible solutions quite well. It is, in the end, a case of whether or not to keep using `alias` method chaining forever or be a good citizen and use to the newer Module#prepend instead.

You can just stay on the 3.x branch of this gem until prometheus-exporter gets with the program and migrates or do one of the more manual patch solutions suggested in the linked issue.
