### ISSUE TITLE
APM hostname collection on detected_hostname raising exceptions

### ISSUE THREAD

**Issue by Esity** [elastic/apm-agent-ruby#1151]
## Describe the bug
The ElasticAPM worker fails to start and the exception points to 
https://github.com/mikker/apm-agent-ruby/blob/9a0d6aa7b52a0b0c699578fe85d0a40db38d4a52/lib/elastic_apm/metadata/system_info.rb#L52-L54

as the exception location

## Steps to reproduce
* Currently running this inside Openshift, ruby 2.5.5, puma 5.4.0, apm gem 4.3.0
* Tried multiple configurations for hostname, service_node_name, etc without success
* Also tried with puma in single mode and clustered mode and it did not make a difference

```
#<Thread:0x00000000034bc960@/opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/base.rb:140 run> terminated with exception (report_on_exception is true):
--
  | /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/metadata/system_info.rb:53:in ``': No such file or directory - hostname (Errno::ENOENT)
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/metadata/system_info.rb:53:in `detect_hostname'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/metadata/system_info.rb:28:in `initialize'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/metadata.rb:26:in `new'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/metadata.rb:26:in `initialize'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/connection.rb:42:in `new'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/connection.rb:42:in `initialize'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/worker.rb:52:in `new'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/worker.rb:52:in `initialize'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/base.rb:141:in `new'
  | from /opt/app-root/src/bundle/ruby/2.5.0/gems/elastic-apm-4.3.0/lib/elastic_apm/transport/base.rb:141:in `block in boot_worker'
```

**Comment by mikker** [comment]
Huh. What happens if you run `hostname` in a terminal on that or a similar machine?

This is a bug. We should catch that and all exceptions when doing a call like that. I'll fix it 👍

**Comment by Esity** [comment]
Quick question, is there a way to override this with a setting/config option so I can get the APM running in this ENV? @mikker

**Comment by mikker** [comment]
Thanks! No way to override the newly introduced `detected_hostname`, unfortunately.
