### ISSUE TITLE
APM ITs for the apm-agent-ruby are failing

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-ruby#1217]
### What

APM ITs for the apm-agent-ruby are failing

![image](https://user-images.githubusercontent.com/2871786/148062109-24f090fc-2e03-4dd6-8ed3-676fb6c40664.png)

### Stacktrace

Logs are stored in the CI -> [see docker logs for the apm-integration-testing](https://apm-ci.elastic.co/job/apm-integration-test-downstream/job/main/128/artifact/docker-ruby-release_latest-master.log/*view*/)

<details><summary>Expand to view the stacktrace</summary>
<p>

```
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] 2022-01-04 04:13:29 +0000: Rack app error handling request { GET /healthcheck }
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] #<Psych::BadAlias: Cannot load database configuration:
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] Unknown alias: default>
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/lib/ruby/3.1.0/psych.rb:370:in `load'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/railties-5.2.6/lib/rails/application/configuration.rb:172:in `database_configuration'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/base.rb:27:in `<main>'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/elastic-apm-4.5.0/lib/elastic_apm/spies.rb:111:in `require'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/query_cache.rb:29:in `run'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:27:in `before'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:426:in `block in make_lambda'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:605:in `catch'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:605:in `block in default_terminator'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:199:in `block in halting'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `each'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:513:in `invoke_before'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:110:in `run!'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:72:in `block in run!'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] <internal:kernel>:90:in `tap'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/execution_wrapper.rb:69:in `run!'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/elastic-apm-4.5.0/lib/elastic_apm/middleware.rb:36:in `call'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[railsapp][apm-integration-testing_agent-ruby-rails][33d4c98cabce181e370528ec3075e046ed5e0d039706cf30464141f79595e0dc][2022-01-04T04:13:29.237Z] /usr/local/bundle/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
</p>
</details>

### How to reproduce it?

1) git clone https://github.com/elastic/apm-integration-testing
2) `APM_AGENT_RUBY_VERSION=release;latest ELASTIC_STACK_VERSION=8.1.0  APM_SERVER_BRANCH_VERSION=master .ci/scripts/ruby.sh`

**Comment by v1v** [comment]
### Further details

The last known working version was about 8 days ago:

![image](https://user-images.githubusercontent.com/2871786/148063020-5cc14423-8459-470f-9f24-338edd6639dc.png)


See [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-test-downstream/detail/main/48/pipeline)

**Comment by v1v** [comment]
I tried with a previous version for the apm-integration-testing with the same outcome:

```
Installing rails 5.2.6
Bundle complete! 8 Gemfile dependencies, 62 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
=> Booting Puma
=> Rails 5.2.6 application starting in production 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 3.1.0-p0), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:8020
Use Ctrl-C to stop
2022-01-04 13:20:15 +0000: Rack app error handling request { GET /healthcheck }
#<Psych::BadAlias: Cannot load database configuration:
Unknown alias: default>
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/usr/local/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/usr/local/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
```

**Comment by v1v** [comment]
I think the latest ruby version 3.1.0 is the one causing those issues since a new docker image was published 8 days ago:
https://hub.docker.com/_/ruby?tab=tags

https://github.com/docker-library/ruby/pull/377

**Comment by v1v** [comment]
Maybe https://github.com/elastic/apm-agent-ruby/pull/1218 will fail?
