### ISSUE TITLE
spec.sh ruby:2.7 grape-1.5 fails locally and in the CI

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-ruby#1220]
`./spec/scripts/spec.sh ruby:2.7 grape-1.5` fails with:

```
Post-install message from sucker_punch:
Sucker Punch v2.0 introduces backwards-incompatible changes.
Please see https://github.com/brandonhilkert/sucker_punch/blob/master/CHANGES.md#200 for details.
Running all specs, including integration

An error occurred while loading ./spec/elastic_apm/agent_spec.rb.
Failure/Error: Bundler.require :default, "test"

NameError:
  uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/grape-1.5.3/lib/grape.rb:15:in `require'
# /usr/local/bundle/gems/grape-1.5.3/lib/grape.rb:15:in `<top (required)>'
# ./spec/spec_helper.rb:31:in `<top (required)>'
# ./spec/elastic_apm/agent_spec.rb:20:in `require'
# ./spec/elastic_apm/agent_spec.rb:20:in `<top (required)>'

An error occurred while loading ./spec/elastic_apm/apm_spec.rb.
Failure/Error: Bundler.require :default, "test"

NameError:
  uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
# /usr/local/bundle/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/grape-1.5.3/lib/grape.rb:15:in `require'
# /usr/local/bundle/gems/grape-1.5.3/lib/grape.rb:15:in `<top (required)>'
# ./spec/spec_helper.rb:31:in `<top (required)>'
# ./spec/elastic_apm/apm_spec.rb:20:in `require'
# ./spec/elastic_apm/apm_spec.rb:20:in `<top (required)>'
```

It also happens in the CI.

The last successful build in the CI was for https://github.com/elastic/apm-agent-ruby/commit/f4aaa2678303d7a8c680194d75376a0f0fa16da5 and the first failure happened in https://github.com/elastic/apm-agent-ruby/commit/d19a649f45a9c244aebf03484e290318fb32ce63

**Comment by estolfo** [comment]
It seems that there was a change added to later versions of Grape that make ActiveSupport load properly. The change is [here](https://github.com/ruby-grape/grape/blob/v1.6.2/lib/grape.rb#L12)
I'll update our matrix to test against the latest minor of Grape that includes this change.
