### ISSUE TITLE
concurrent-ruby deprecated TimerTask timeout_interval option

### ISSUE THREAD

**Issue by jhass** [elastic/apm-agent-ruby#1249]
Updating to concurrent-ruby 1.1.10 triggers the following deprecation warnings while using elastic-apm 4.5.0:

```
TimeTask timeouts are now ignored as these were not able to be implemented correctly
```

I modified stuff to get some backtraces:

```
TimeTask timeouts are now ignored as these were not able to be implemented correctly
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:28:in `block in initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:25:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_executor_service.rb:12:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/timer_task.rb:182:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/timer_task.rb:224:in `execute'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/base.rb:114:in `create_watcher'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/base.rb:64:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:117:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:62:in `block in start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:51:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:51:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm.rb:60:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/rails.rb:46:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/railtie.rb:38:in `block in <class:Railtie>'
[...]



TimeTask timeouts are now ignored as these were not able to be implemented correctly
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:28:in `block in initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:25:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_executor_service.rb:12:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/timer_task.rb:182:in `initialize'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/object.rb:59:in `new'
/Users/j.hass/.gem/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/timer_task.rb:224:in `execute'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/metrics.rb:77:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:119:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:62:in `block in start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:51:in `synchronize'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/agent.rb:51:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm.rb:60:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/rails.rb:46:in `start'
/Users/j.hass/.gem/ruby/3.1.0/gems/elastic-apm-4.5.0/lib/elastic_apm/railtie.rb:38:in `block in <class:Railtie>'
```

**Comment by slhck** [comment]
It seems this has been solved in https://github.com/elastic/apm-agent-ruby/pull/1255.

**Comment by jaggederest** [comment]
Thanks @slhck - yes this should be fixed now, let me know if you see any other warning annoyances. Happy hunting with 4.5.1 🎉
