### ISSUE TITLE
Faraday errors after updating to 4.6.1

### ISSUE THREAD

**Issue by cernyjakub** [elastic/apm-agent-ruby#1370]
After updating my rails 7 app running on ruby 2.7, I started to received errors like this:

```
Faraday::RackBuilder::StackLocked: can't modify middleware stack after making a request
  from faraday (2.7.4) lib/faraday/rack_builder.rb:220:in `raise_if_locked'
  from faraday (2.7.4) lib/faraday/rack_builder.rb:96:in `use'
  from faraday (2.7.4) lib/faraday/rack_builder.rb:242:in `use_symbol'
  from faraday (2.7.4) lib/faraday/rack_builder.rb:107:in `response'
  from forwardable.rb:235:in `response'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/faraday.rb:105:in `block (2 levels) in run_request'
  from elastic-apm (4.6.1) lib/elastic_apm/spies.rb:74:in `block in without_net_http'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/net_http.rb:42:in `disable_in'
  from elastic-apm (4.6.1) lib/elastic_apm/spies.rb:73:in `without_net_http'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/faraday.rb:103:in `block in run_request'
  from elastic-apm (4.6.1) lib/elastic_apm.rb:302:in `with_span'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/faraday.rb:97:in `run_request'
  from elastic-transport (8.2.0) lib/elastic/transport/transport/http/faraday.rb:41:in `block in perform_request'
  from elastic-transport (8.2.0) lib/elastic/transport/transport/base.rb:296:in `perform_request'
  from elastic-transport (8.2.0) lib/elastic/transport/transport/http/faraday.rb:36:in `perform_request'
  from elastic-transport (8.2.0) lib/elastic/transport/client.rb:176:in `perform_request'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/elasticsearch.rb:77:in `block in perform_request'
  from elastic-apm (4.6.1) lib/elastic_apm.rb:302:in `with_span'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/elasticsearch.rb:72:in `perform_request'
  from elasticsearch (8.6.0) lib/elasticsearch.rb:71:in `method_missing'
  from elasticsearch-api (8.6.0) lib/elasticsearch/api/actions/bulk.rb:69:in `bulk'
  from searchkick (5.2.1) lib/searchkick/indexer.rb:22:in `perform'
  from searchkick (5.2.1) lib/searchkick.rb:226:in `block in callbacks'
  from activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `instrument'
  from searchkick (5.2.1) lib/searchkick.rb:225:in `callbacks'
  from searchkick (5.2.1) lib/searchkick/record_indexer.rb:132:in `block in maybe_bulk'
  from searchkick (5.2.1) lib/searchkick/record_indexer.rb:154:in `with_retries'
  from searchkick (5.2.1) lib/searchkick/record_indexer.rb:131:in `maybe_bulk'
  from searchkick (5.2.1) lib/searchkick/record_indexer.rb:92:in `import_inline'
  from searchkick (5.2.1) lib/searchkick/record_indexer.rb:79:in `reindex_items'
  from searchkick (5.2.1) lib/searchkick/reindex_v2_job.rb:14:in `perform'
  from activejob (7.0.4.2) lib/active_job/execution.rb:59:in `block in _perform_job'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  from sentry-raven (3.1.2) lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
  from activejob (7.0.4.2) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.4.2) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  from activejob (7.0.4.2) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
  from activejob (7.0.4.2) lib/active_job/execution.rb:58:in `_perform_job'
  from activejob (7.0.4.2) lib/active_job/instrumentation.rb:20:in `_perform_job'
  from activejob (7.0.4.2) lib/active_job/execution.rb:46:in `perform_now'
  from activejob (7.0.4.2) lib/active_job/instrumentation.rb:14:in `block in perform_now'
  from activejob (7.0.4.2) lib/active_job/instrumentation.rb:25:in `block in instrument'
  from activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `instrument'
  from activejob (7.0.4.2) lib/active_job/instrumentation.rb:35:in `instrument'
  from activejob (7.0.4.2) lib/active_job/instrumentation.rb:14:in `perform_now'
  from activejob (7.0.4.2) lib/active_job/logging.rb:18:in `block in perform_now'
  from activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
  from activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'
  from activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'
  from activejob (7.0.4.2) lib/active_job/logging.rb:25:in `tag_logger'
  from activejob (7.0.4.2) lib/active_job/logging.rb:18:in `perform_now'
  from activejob (7.0.4.2) lib/active_job/execution.rb:24:in `block in execute'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  from activejob (7.0.4.2) lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
  from activesupport (7.0.4.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.4.2) lib/active_support/execution_wrapper.rb:88:in `wrap'
  from activesupport (7.0.4.2) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (7.0.4.2) lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
  from activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
  from activejob (7.0.4.2) lib/active_job/execution.rb:22:in `execute'
  from activejob (7.0.4.2) lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:202:in `execute_job'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
  from sidekiq (6.5.8) lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
  from elastic-apm (4.6.1) lib/elastic_apm/spies/sidekiq.rb:35:in `call'
  from sidekiq (6.5.8) lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
  from sentry-raven (3.1.2) lib/raven/integrations/sidekiq/cleanup_middleware.rb:7:in `call'
  from sidekiq (6.5.8) lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
  from sidekiq (6.5.8) lib/sidekiq/middleware/chain.rb:182:in `invoke'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:169:in `block in process'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/job_retry.rb:113:in `local'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (7.0.4.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4.2) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (7.0.4.2) lib/active_support/execution_wrapper.rb:92:in `wrap'
  from activesupport (7.0.4.2) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.5.8) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:263:in `stats'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/job_retry.rb:80:in `global'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.5.8) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:168:in `process'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.5.8) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:8:in `watchdog'
  from sidekiq (6.5.8) lib/sidekiq/component.rb:17:in `block in safe_thread'
```
This error was emited from Searchkick gem background indexing using Sidekiq. Also, this happened in all actions talking to Elasticsearch. I assume there is a middleware collision in Faraday, when it is used to talk to Elastic.

I am not a system expert, just wanted to share this. Downgrading to 4.6.0 fixes this issue, so it might be a regression.

**Comment by estolfo** [comment]
Hi @cernyjakub thanks for reporting this. Please continue to use v4.6.0 of the agent until we can fix this.

**Comment by ericproulx** [comment]
@estolfo same issue :(

**Comment by ericproulx** [comment]
> @ericproulx any ideas on how to address this? It didn't show up in your testing of the [PR](https://github.com/elastic/apm-agent-ruby/pull/1368), right?

I will investigate and come back. We just had the issue a few minutes ago :(

**Comment by estolfo** [comment]
Do you know what's different between the code you tested and what's having issues now? I see this issue that might explain what's going on https://github.com/honeycombio/beeline-ruby/issues/15#issuecomment-489346557

**Comment by ericproulx** [comment]
> Do you know what's different between the code you tested and what's having issues now? I see this issue that might explain what's going on [honeycombio/beeline-ruby#15 (comment)](https://github.com/honeycombio/beeline-ruby/issues/15#issuecomment-489346557)

I tried locally in development mode only and I've posted a [screenshot](https://github.com/elastic/apm-agent-ruby/pull/1368#issuecomment-1439009537) from my local ELK stack. I guess there's is something different in production mode :(

**Comment by ericproulx** [comment]
@estolfo as seen as an app call Elasticsearch, we have the the "can't modify stack". We a simple faraday connection like this
```ruby
c = Faraday.new(url: 'https://httpstat.us/404') do |faraday|
  faraday.use Faraday::Response::RaiseError
  faraday.response :json, content_type: /\bjson$/
  faraday.adapter Faraday.default_adapter # make requests with Net::HTTP
end
c.get
```
it works as expected. I continue my investgation.

**Comment by estolfo** [comment]
Hi @ericproulx thanks so much for the PR! What does it show when you look at the CLA info on the PR? Does it show that you've signed it?

**Comment by ericproulx** [comment]
> Hi @ericproulx thanks so much for the PR! What does it show when you look at the CLA info on the PR? Does it show that you've signed it?

CLA - All commits passed the check

**Comment by ericproulx** [comment]
Although, can't run the tests : `The PR is not allowed to run in the CI yet`. I don't know what I'm missing

**Comment by estolfo** [comment]
Yeah, only members of the `elastic` org can trigger tests. I've just done it manually. I'll look into the CLA issue and let you know. Thanks!

**Comment by ericproulx** [comment]
I'll continue testing on my side but rescuing exceptions seems less invasive than the middleware and it won't cause the StackLocked for sure
