### ISSUE TITLE
`rails middleware` throws an error

### ISSUE THREAD

**Issue by bguban** [elastic/apm-agent-ruby#560]
Hey, I installed `elastic-apm (3.0.0)` into my app and now `rails middleware` throws an error:
```
...
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/elastic-apm-3.0.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/bguban/.rvm/gems/ruby-2.6.4@price_manager/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
```

**Comment by estolfo** [comment]
Hi @bguban Thanks for reporting this. We'll look into it and follow-up soon.

**Comment by estolfo** [comment]
Hi again, I've just tested with a Rails v5.2.3 app and `elastic-apm` gem `3.0.0` and could successfully run `rails middleware`. So if you wouldn't mind answering the following questions, we can investigate further.
- Can you provide your `Gemfile.lock`?
- Did you update any other gems?
- If you downgrade the gem to the latest in the 2.x series (`2.12.0`), does the error go away?

Here is my test, let me know if anything is inconsistent with your setup. Thanks!
```
$ rails -v
Rails 5.2.3
$ bundle list
Gems included by the bundle:
  * actionmailer (5.2.3)
  * actionpack (5.2.3)
  * actionview (5.2.3)
  * activejob (5.2.3)
  * activemodel (5.2.3)
  * activerecord (5.2.3)
  * activestorage (5.2.3)
  * activesupport (5.2.3)
.....
  * elastic-apm (3.0.0)
  
$ rails middleware
use ElasticAPM::Middleware
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
run MyApp::Application.routes
```

**Comment by bguban** [comment]
Hi @estolfo, looks like I found a problem, it conflicts with `bugsnag` gem

**Comment by estolfo** [comment]
Ah, I see. Did you also upgrade that gem?
Is there anything we can do for this or can we close the ticket?

**Comment by bguban** [comment]
I have the latest version of `bugsnag` gem. Looks like `::Rake::Task.execute` is overridden by both of gems. I didn't find a way to use both of the gems together.

**Comment by mikker** [comment]
I'll copy my comment from the PR as it's probably better to have the discussion here:

Hi @bguban! Thank you for contributing this. Ruby doesn't do well when you mix `prepend` and `alias` ([see](https://github.com/elastic/apm-agent-ruby/issues/379#issuecomment-500857044)) so I'm hesitant to merge this.

Could you perhaps fix your problems by changing the load order of your gems? To make it work with both implementations, make sure to load the one with  `Module#prepend` _after_ the one with `alias`.

**Comment by lreuven** [comment]
@bmorelli25 can we create similar entry in our docs? ( see Mikkel response)

**Comment by bguban** [comment]
Hi @mikker, I tried to change the order but it didn't help. 
```
# Gemfile
gem "elastic-apm", require: false
gem "bugsnag", require: false
```
```
#config/application.rb
require "elastic-apm"
require "bugsnag"
```
Maybe I do something wrong?  Any other ideas?

**Comment by mikker** [comment]
I couldn't get the load order to change anything either. Disabling the `rake` instrumentation works though. Either way you do it, it'll let you run both gems side-by-side:

```yaml
# config/elastic_apm.yml
disabled_instrumentations: ['json','rake']
```

```ruby
# config/application.rb
config.elastic_apm.disabled_instrumentations << 'rake'
```

```sh
$ ELASTIC_APM_DISABLED_INSTRUMENTATIONS=json,rake rails middleware
```

**Comment by Intrepidd** [comment]
Hi, I was about to open an issue as I encountered the exact same problem when running `webpacker:compile`. The suggested workaround is fine but it should be documented IMO :) 

Thanks !
