### ISSUE TITLE
Concurrency issue in `add_filter`

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-ruby#582]
Occasionally we see the following error

```
expected no Exception, got #<RuntimeError: can't add a new key into hash during iteration> with backtrace:
# ./lib/elastic_apm/transport/filters.rb:22:in `add'
# ./lib/elastic_apm/transport/base.rb:74:in `add_filter'
# ./lib/elastic_apm/agent.rb:232:in `add_filter'
# ./lib/elastic_apm.rb:324:in `add_filter'
# ./spec/elastic_apm_spec.rb:190:in `block in <main>'
```

which is indicative of two threads trying to access/mutate the filter list at the same time. We should investigate and add a lock.

**Comment by mikker** [comment]
Fixed by #624
