### ISSUE TITLE
ElasticAPM not reporting transactions from Rails and claiming connection issues

### ISSUE THREAD

**Issue by mmuehlberger** [elastic/apm-agent-ruby#707]
## Describe the bug

We have a standard Rails 6.0.1 API-only app (without ActiveRecord) running on ECS. We're not able to connect to the APM server through Rails with the current version of the gem to show transactions for the Rails server, but we are for Sidekiq. The Sidekiq container runs next to Rails in the same task.

As a debugging step I made a manual request to the APM server using Faraday in an initializer
(`Faraday.get(ENV['ELASTIC_APM_SERVER_URL'], {}, { 'Authorization' => "Bearer #{ENV['ELASTIC_APM_SECRET_TOKEN']}" })`) which returns a successful status and the correct payload from the server.

We're running puma in a fairly standard configuration (see below).

_The same thing happens for us with a Rails 5.2.0 app, running the thin web server. Only errors are reported to APM, but no transactions._

### Puma config

```ruby
max_threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }
min_threads_count = ENV.fetch('RAILS_MIN_THREADS') { max_threads_count }
threads min_threads_count, max_threads_count

port        ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RAILS_ENV') { 'development' }
pidfile     ENV.fetch('PIDFILE') { 'tmp/server.pid' }
workers     ENV.fetch('WEB_CONCURRENCY') { 2 }

preload_app!
```

### Logs
```
[1] Puma starting in cluster mode...
[1] * Version 4.3.1 (ruby 2.6.5-p114), codename: Mysterious Traveller
[1] * Min threads: 5, max threads: 5
[1] * Environment: production
[1] * Process workers: 2
[1] * Preloading application
[3.4.0] Starting agent, reporting to https://apm.my-company.com:443
[ElasticAPM] Starting CentralConfig
[ElasticAPM] [PID:1]: Starting Transport
[ElasticAPM] [PID:1]: Booting worker...
[ElasticAPM] Starting instrumenter
[ElasticAPM] Starting metrics
[ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::CpuMemSet'
[ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::VMSet'
[ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::BreakdownSet'
[ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::TransactionSet'
[ElasticAPM] Collecting metrics
[ElasticAPM] [THREAD:47133928391280]: Opening new request
[ElasticAPM] Registering subscriber
[ElasticAPM] Failed fetching config: 400 Bad Request, trying again in 300 seconds
[1] * Listening on ssl://0.0.0.0:3000?key=local.key&cert=local.crt&verify_mode=none
[1] ! WARNING: Detected 6 Thread(s) started in app boot:
[1] ! #<Thread:0x000055bc72209700@/bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:317 sleep_forever> - /bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `pop'
[1] ! #<Thread:0x000055bc721e0a58@/bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:317 sleep> - /bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:46:in `sleep'
[1] ! #<Thread:0x000055bc721e04e0@/bundle/vendor/ruby/2.6.0/gems/elastic-apm-3.4.0/lib/elastic_apm/transport/base.rb:122 sleep_forever> - /bundle/vendor/ruby/2.6.0/gems/elastic-apm-3.4.0/lib/elastic_apm/transport/worker.rb:40:in `pop'
[1] ! #<Thread:0x000055bc7222ad60@/bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:317 sleep_forever> - /bundle/vendor/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `pop'
[1] ! #<Thread:0x000055bc72384508 sleep> - 
[1] ! #<Thread:0x000055bc72429da0@/bundle/vendor/ruby/2.6.0/gems/elastic-apm-3.4.0/lib/elastic_apm/transport/connection/http.rb:90 sleep> - /bundle/vendor/ruby/2.6.0/gems/http-4.3.0/lib/http/request/body.rb:37:in `copy_stream'
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 21) booted, phase: 0
[1] - Worker 1 (pid: 22) booted, phase: 0
[ElasticAPM] [THREAD:47133928475520]: Closing request with reason timeout
[ElasticAPM] [THREAD:47133928475520]: APM Server not responding in time, terminating request
[ElasticAPM] Collecting metrics
[ElasticAPM] [THREAD:47133928391280]: Opening new request
[ElasticAPM] [THREAD:47133928475520]: Closing request with reason timeout
[ElasticAPM] Closing writer with reason timeout
[ElasticAPM] APM Server responded with status 202
[ElasticAPM] Collecting metrics
[ElasticAPM] [THREAD:47133928391280]: Opening new request
[ElasticAPM] [THREAD:47133928475520]: Closing request with reason timeout
[ElasticAPM] Closing writer with reason timeout
[ElasticAPM] APM Server responded with status 202
```

## Expected behavior

No error message and transactions showing up in Kibana.

## Environment
- **OS**: Docker (ruby:2.6.5-alpine)
- **Ruby version**: 2.6.5
- **Framework and version**: Rails 6.0.1]
- **APM Server version**: 7.5.2
- **Agent version**: 3.4.0

**Comment by mikker** [comment]
Hi @mmuehlberger!

I just ran some tests with the same config and even though I get the same thread warnings, the data came through just fine.

To be sure we're on the same page, as the copy might be misleading: _request timeout_ is not a bad thing in this case. It means the request has outlived its `api_request_time` and is being closed on purpose. APM Server then responds correctly, successfully with a `202` status.

**Comment by mmuehlberger** [comment]
Thanks for looking into this, I’ve spent a couple of hours on it already, that’s why I opened up the issue.

My connection issue claim was referring to `[ElasticAPM] [THREAD:47133928475520]: APM Server not responding in time, terminating request`. 

We’re receiving metrics and errors fine, but no transactions (which I would expect for requests).

To clarify further, there’s no load other than 2 testing Rails apps on the apm server which is running redundantly itself.

I’m going to try again with a complete vanilla Rails app and either close or update the issue.

**Comment by mmuehlberger** [comment]
The issue was with a misconfigured ignore pattern (I put `['/healthz']` in the environment variable), which lead to no requests being captured. 

Might be a different issue, since nothing should be ignored then.

**Comment by mikker** [comment]
Good to know! Thanks for updating the issue 👍
