### ISSUE TITLE
Conflict with the Airbrake gem

### ISSUE THREAD

**Issue by paul-mesnilgrente** [elastic/apm-agent-ruby#753]
## Describe the bug

I upgraded to the latest version of Airbrake (10.0.2) and Elastic-APM (3.6.0) and I started to have a `SystemStackError` in my controller. After some time I found that the stack was too deep. Logging the backtrace showed:

```
"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm/spies/net_http.rb:72:in `block in request'"
"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm.rb:273:in `with_span'"
"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm/spies/net_http.rb:62:in `request'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rails/net_http.rb:11:in `block in request'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rack.rb:26:in `block in capture_timing'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:29:in `span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `block in span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `tap'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rack.rb:25:in `capture_timing'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rails/net_http.rb:10:in `request'"

"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm/spies/net_http.rb:72:in `block in request'"
"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm.rb:273:in `with_span'"
"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm/spies/net_http.rb:62:in `request'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rails/net_http.rb:11:in `block in request'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rack.rb:26:in `block in capture_timing'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:29:in `span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `block in span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `tap'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-ruby-4.13.3/lib/airbrake-ruby/timed_trace.rb:18:in `span'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rack.rb:25:in `capture_timing'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rails/net_http.rb:10:in `request'"

"/app/vendor/cache/ruby/2.6.0/gems/elastic-apm-3.6.0/lib/elastic_apm/spies/net_http.rb:72:in `block in request'"
```

You can see here that elastic-apm is called by airbrake which is calling airbrake, and that in a loop

I tried the same code with elastic-apm 3.1.0 and airbrake 9.5.5 and it worked fine (that's the only other config I tried)

## Steps to reproduce
1. Install elastic-apm 3.6.0 (I only tested that one)
2. Install airbrake 10.0.2 (I only tested that one)
3. Run a code calling an API with RestClient. My last lines called before entering the loop:

```
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rack.rb:25:in `capture_timing'"
"/app/vendor/cache/ruby/2.6.0/gems/airbrake-10.0.2/lib/airbrake/rails/net_http.rb:10:in `request'"
"/app/vendor/cache/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:473:in `net_http_do_request'"
"/app/vendor/cache/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:733:in `block in transmit'"
"/usr/local/lib/ruby/2.6.0/net/http.rb:920:in `start'"
"/app/vendor/cache/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'"
"/app/vendor/cache/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'"
"/app/vendor/cache/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'"
```

## Expected behavior

No conflicts with Airbrake.

## Environment

- **OS**: [ruby:2.6.5-alpine](https://hub.docker.com/_/ruby)
- **Ruby version**: 2.6.5
- **Framework and version**: Rails 5.1.7
- **APM Server version**: 
- **Agent version**: 3.6.0 (my gem version)

Related issue: https://github.com/airbrake/airbrake/issues/1080

**Comment by mikker** [comment]
Hi Paul! This comment on the related issue describes the problem correctly: https://github.com/airbrake/airbrake/issues/1080#issuecomment-609569006.

It's something we've tried to fix once but ended up reverting: #394. I'm willing to reconsider but hesitant as it might break stuff for everyone who has the agent running without this problem currently.

Luckily there is a _"fix"_ for the problem: If you mix the two methods, **`class_eval` must go before `Module#prepend`**. In this case meaning, put `gem "elastic_apm"` above `gem "airbrake"` in your `Gemfile`. Please let us know if that works.

**Comment by estolfo** [comment]
Releated to https://github.com/elastic/apm-agent-ruby/issues/379

**Comment by paul-mesnilgrente** [comment]
Yeah that worked for me @mikker . Thanks for your help :)

**Comment by mrudult** [comment]
We are still experiencing this issue with version `4.1.0` of `elastic-apm`

```
#<Thread:0x000056063e834380@/applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:140 run> terminated with exception (report_on_exception is true):
      01 /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm.rb:84:in `agent': stack level too deep (SystemStackError)
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm.rb:93:in `current_transaction'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/spies/http.rb:31:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:10:in `block in perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:9:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/spies/http.rb:32:in `perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rails/http.rb:10:in `block in perform'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
      01   ... 9349 levels...
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/worker.rb:52:in `new'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/worker.rb:52:in `initialize'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:141:in `new'
      01  from /applications/rails-app/shared/bundle/ruby/2.6.0/gems/elastic-apm-4.1.0/lib/elastic_apm/transport/base.rb:141:in `block in boot_worker'
```

**Comment by Reinkaos** [comment]
This issue appears to be happening again, regardless of the order of the airbrake/ elastic apm gem. I have tried above and below to no success, but does work once I remove the Airbrake gem.

**Comment by Reinkaos** [comment]
Note that it works fine with elastic apm gem 3.15.1 :). Hope that helps!
