### ISSUE TITLE
Error: "undefined method `done' for nil:NilClass" in testing environment with delayed_job

### ISSUE THREAD

**Issue by fsedano** [elastic/apm-agent-ruby#873]
## Steps to reproduce

1. On the test, use Delayed::Worker.delay_jobs = false, to execute jobs realtime
2. When running the test, the following backtrace is seen
```
Backtrace: /usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/delayed_job.rb:47:in `rescue in invoke_job'
/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/delayed_job.rb:45:in `invoke_job'
/usr/local/bundle/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/delayed_job.rb:35:in `invoke_job'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:19:in `block (2 levels) in enqueue_job'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:17:in `block in enqueue_job'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:16:in `tap'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:16:in `enqueue_job'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:12:in `enqueue'
/usr/local/bundle/gems/delayed_job-4.1.8/lib/delayed/message_sending.rb:11:in `method_missing'
```
3. test fails

## Expected behavior
Test to succeed

## Environment

- **OS**: Linux
- **Ruby version**:2.6.6
- **Framework and version**: Rails 5.2.4.3, delayed_job 4.1.8
- **APM Server version**: 
- **Agent version**: 3.10.1

**Comment by mikker** [comment]
Hi @fsedano! This is a bug – thanks for finding and reporting it. It happens when using DJ and no agent instance running. I've fixed this in a PR, releasing it as soon as the build is green!
