### ISSUE TITLE
[APM] - Ruby APM agent crashes due to 1.0:Float

### ISSUE THREAD

**Issue by himberjack** [elastic/apm-agent-ruby#918]
**Versions**
Kibana: 7.10
APM Server: 7.10

If elastic-apm gem is > 3.10.x we are getting:

```
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/metadata.rb:28:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/metadata.rb:28:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/connection.rb:42:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/connection.rb:42:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/worker.rb:52:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/worker.rb:52:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/base.rb:141:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/base.rb:141:in `block in boot_worker'
#<Thread:0x0000561f5383e320 /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/base.rb:140 run> terminated with exception (report_on_exception is true):/usr/local/bundle/gems/http-3.3.0/lib/http/chainable.rb:104:in `timeout': undefined method `to_sym' for 0.1:Float (NoMethodError)
    Did you mean?  to_s	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/metadata/cloud_info.rb:34:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/metadata.rb:28:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/metadata.rb:28:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/connection.rb:42:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/connection.rb:42:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/worker.rb:52:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/worker.rb:52:in `initialize'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/base.rb:141:in `new'	
from /usr/local/bundle/gems/elastic-apm-3.12.1/lib/elastic_apm/transport/base.rb:141:in `block in boot_worker'
```

This is coming from the config server

**Comment by dgieselaar** [comment]
@himberjack I've moved to this to the apm-agent-ruby repo as this seems to be an agent-specific issue.

**Comment by mikker** [comment]
Hi @himberjack! Thanks for reporting this. Can you share your agent config? Without the sensible parts of course.

**Comment by himberjack** [comment]
service_name: 'xxxx'
secret_token: 'yyyy'
server_url: 'zzzzzz'

and in the Config Manager in the Elastic Cloud I have transaction_sample_rate 0.1

**Comment by mikker** [comment]
Thanks for that. I found the error and pushed a PR. Has to do with API changes between Http.rb 3.x and 4.x. Will ship a release as soon as CI finishes.

**Comment by himberjack** [comment]
Thank you very much - appreciate it

**Comment by mikker** [comment]
Let me know if 3.13.0 doesn't fix this for you.

**Comment by himberjack** [comment]
Seems to work

Thank you
