### ISSUE TITLE
JRuby fails with  `Resource temporarily unavailable`

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#920]
```
Failure/Error: Bundler.require :default, "test"
[2020-12-22T13:14:05.560Z] 
[2020-12-22T13:14:05.560Z] Errno::EAGAIN:
[2020-12-22T13:14:05.560Z]   Resource temporarily unavailable - Resource temporarily unavailable
```

**Comment by mikker** [comment]
cc @elastic/observablt-robots not sure what's up. Seems to be happening on runs with our self-hosted jruby images.

**Comment by kuisathaverat** [comment]
locally happens the same thing, running the script `./spec/scripts/spec.sh docker.elastic.co/observability-ci/jruby:9.2-13-jdk rails-6.0`

```
Coverage may be inaccurate; set the "--debug" command line option, or do JRUBY_OPTS="--debug" or set the "debug.fullTrace=true" option in your .jrubyrc
/usr/local/bundle/jruby/2.5.0/gems/simplecov-0.20.0/lib/simplecov.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
An error occurred while loading ./spec/elastic_apm/agent_spec.rb.
Failure/Error: Bundler.require :default, 'test'
Errno::EAGAIN:
  Resource temporarily unavailable - Resource temporarily unavailable
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/editor.rb:19:in `block in default'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/editor.rb:18:in `default'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/config.rb:186:in `initialize'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:327:in `reset_defaults'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:337:in `init'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:388:in `<main>'
# /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry.rb:61:in `<main>'
# ./spec/spec_helper.rb:37:in `<main>'
# ./spec/elastic_apm/agent_spec.rb:20:in `<main>'
```

it fails on `spec/spec_helper.rb`  line 37 `Bundler.require :default, 'test'`

**Comment by kuisathaverat** [comment]
It is failing in other stages with a similar issue, a retry of the test seems to fix the issue so it is something flaky downloading resources

```
[2020-12-22T13:54:36.487Z] NOTE: Picked up JDK_JAVA_OPTIONS: 
[2020-12-22T13:54:46.523Z] Coverage may be inaccurate; set the "--debug" command line option, or do JRUBY_OPTS="--debug" or set the "debug.fullTrace=true" option in your .jrubyrc
[2020-12-22T13:54:46.523Z] /usr/local/bundle/jruby/2.5.0/gems/simplecov-0.20.0/lib/simplecov.rb:344: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
[2020-12-22T13:54:46.785Z] 
[2020-12-22T13:54:46.785Z] An error occurred while loading ./spec/integration/skip_require_patch_spec.rb.
[2020-12-22T13:54:46.785Z] Failure/Error: Bundler.require :default, "test"
[2020-12-22T13:54:46.785Z] 
[2020-12-22T13:54:46.785Z] Errno::EAGAIN:
[2020-12-22T13:54:46.785Z]   Resource temporarily unavailable - Resource temporarily unavailable
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/editor.rb:19:in `block in default'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/editor.rb:18:in `default'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/config.rb:186:in `initialize'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:327:in `reset_defaults'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:337:in `init'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry/pry_class.rb:388:in `<main>'
[2020-12-22T13:54:46.785Z] # /usr/local/bundle/jruby/2.5.0/gems/pry-0.13.1-java/lib/pry.rb:61:in `<main>'
[2020-12-22T13:54:46.785Z] # ./spec/spec_helper.rb:31:in `<main>'
[2020-12-22T13:54:46.785Z] # ./spec/integration_helper.rb:1:in `<main>'
[2020-12-22T13:54:46.785Z] # ./spec/integration/skip_require_patch_spec.rb:23:in `<main>'
[2020-12-22T13:54:46.785Z] No examples found.
```

**Comment by kuisathaverat** [comment]
The debug mode does not help, the same error about 50% of times locally, I have open to enable debug on JRuby correctly https://github.com/elastic/apm-agent-ruby/pull/921

**Comment by kuisathaverat** [comment]
I've added retries to `bundle` this makes this issue disappear. Now we have to deal with 80 tests that fail I dunno why https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-921/detail/PR-921/2/tests

**Comment by kuisathaverat** [comment]
@mikker the issue happens since these changes https://github.com/elastic/apm-agent-ruby/pull/915 only on JRuby 9.2-13-jdk and rails-6.0

**Comment by mikker** [comment]
That sounds very weird. Can't see what could be going wrong. @estolfo ?

**Comment by estolfo** [comment]
I'll take a look

**Comment by estolfo** [comment]
This was an issue with installing pry with jruby. [We've removed pry from the Gemfile](https://github.com/elastic/apm-agent-ruby/pull/924/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fL26) so we can now avoid this.
