### ISSUE TITLE
Binary Redis payloads break APM reporting

### ISSUE THREAD

**Issue by cheald** [elastic/apm-agent-ruby#94]
We have some legacy code which is using Redis for session management, which among other things uses Marshal.dump to store Ruby objects in Redis. This results in non-UTF-8 byte sequences in the command, which breaks Elastic APM when it tries to dump the payload to UTF-8 JSON.

Here's a quick repro case (I added this to the Redis injector, but it doesn't really belong there. It demonstrates the break though.)

```ruby
    it "breaks on binary query payloads" do
      redis = ::Redis.new
      ElasticAPM.start

      transaction = ElasticAPM.transaction 'T' do
        redis.set("session", Marshal.dump(0xdeadbee))
      end.submit 200

      ElasticAPM.agent.instance_variable_get("@serializers").transactions.build_all([transaction]).to_json
      ElasticAPM.stop
    end
```

```
  2) Injectors::RedisInjector breaks on binary query payloads
     Failure/Error:
                 alias :"__without_apm_#{method}" :"#{method}"

                 def #{method}(*args, &block)
                   unless ElasticAPM.current_transaction
                     return __without_apm_#{method}(*args, &block)
                   end

                   ElasticAPM.span "#{name}", "#{type}" do
                     __without_apm_#{method}(*args, &block)

     Encoding::UndefinedConversionError:
       "\xEE" from ASCII-8BIT to UTF-8
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/core_ext/object/json.rb:34:in `encode'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/core_ext/object/json.rb:34:in `to_json'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/json/encoding.rb:57:in `to_json'
     # ./lib/elastic_apm/span_helpers.rb:20:in `generate'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/json/encoding.rb:101:in `stringify'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/json/encoding.rb:35:in `encode'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/json/encoding.rb:22:in `encode'
     # /home/chris/.rvm/gems/ruby-2.4.3/gems/activesupport-4.2.10/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # ./spec/elastic_apm/injectors/redis_spec.rb:35:in `block (2 levels) in <module:ElasticAPM>'
```

Tangentially, I'd like the ability to exclude the arguments to the Redis command from the APM, since I don't really want large Redis payloads with sensitive being captured and stored in the APM itself.

**Comment by cheald** [comment]
Something like this works, too, though the cost of pre-emptively attempting string and encoding conversion (and the potential for high-throughput exception handling) is questionable:

```diff
           def call(command, &block)
             name = command[0].upcase
-            statement =
-              format('%s %s', name, command[1..command.length].join(' '))
+            args = command.slice(1..-1).map do |val|
+              begin
+                val.to_s.encode("UTF-8")
+              rescue Encoding::UndefinedConversionError
+                "<binary>"
+              end
+            end
+            statement = format('%s %s', name, args.join(' '))
             context = Span::Context.new(
               statement: statement,
               type: 'redis'
```

**Comment by mikker** [comment]
Hi @cheald! Thanks for reporting this. After a discussion with a co-worker we agreed with your concern about actually storing the payloads. So, I am going to _fix_ this by just omitting them completely for everyone.

**Comment by cheald** [comment]
Thanks for the quick response!
